"""Build a pytest file that replays one session's model steps offline."""

from __future__ import annotations

import pprint
import re
from pathlib import Path
from typing import Any

from microcode.turn_tape import load_tape
from microcode.types import ChatMessage

_SAFE = re.compile(r"[^A-Za-z0-9._-]+")
RESULT_LIMIT = 4000


def export_fixture(
    cwd: str,
    messages: list[ChatMessage],
    *,
    session_id: str = "",
) -> str:
    turns = build_turns(messages, load_tape(cwd), session_id=session_id)
    if not turns:
        return "No user turn to save as a fixture.\n"
    system = ""
    for message in messages:
        if message.get("role") == "system":
            system = str(message.get("content") or "")
            break
    text = render_fixture(session_id or "session", system, turns)
    safe = _SAFE.sub("-", session_id or "session").strip("-") or "session"
    path = Path(cwd) / ".microcode" / "fixtures" / f"{safe}.py"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return (
        f"Wrote {path}\n"
        f"{len(turns)} turn(s). Replay with:\n"
        f"python -m pytest {path} -q\n"
    )


def build_turns(
    messages: list[ChatMessage],
    tape_rows: list[dict[str, Any]] | None = None,
    *,
    session_id: str = "",
) -> list[dict[str, Any]]:
    """One dict per user message: user text, model steps, tool results.

    Full tool inputs come from the session. The tape only supplies how many
    calls belonged to the same model reply. Clipped tape text is not copied.
    """

    groups = _tape_groups(tape_rows or [], session_id)
    turns: list[dict[str, Any]] = []
    index = 0
    items = list(messages)
    while index < len(items):
        if items[index].get("role") != "user":
            index += 1
            continue
        user = str(items[index].get("content") or "")
        index += 1
        segment: list[ChatMessage] = []
        while index < len(items) and items[index].get("role") != "user":
            segment.append(items[index])
            index += 1
        tape_models = groups.pop(0) if groups else []
        turns.append(_turn_from_segment(user, segment, tape_models))
    return turns


def render_fixture(session_id: str, system: str, turns: list[dict[str, Any]]) -> str:
    payload = pprint.pformat(turns, width=100, sort_dicts=False)
    system_lit = pprint.pformat(system, width=100)
    return f'''"""Replay session {session_id} without a model API.

Generated by /fixture. Tool arguments come from the session transcript.
Run from the repository root:

    python -m pytest <this file> -q
"""

from microcode.agent_loop import run_agent_turn
from microcode.tooling import ToolDefinition, ToolRegistry, ToolResult
from microcode.types import AgentStep

SYSTEM = {system_lit}
TURNS = {payload}


class ScriptedModel:
    def __init__(self, steps: list[dict]) -> None:
        self._steps = steps
        self.calls = 0
        self.seen_calls: list[tuple[str, object]] = []

    def next(self, messages, on_text_delta=None) -> AgentStep:
        step = self._steps[self.calls]
        self.calls += 1
        if step["type"] == "tool_calls":
            return AgentStep(type="tool_calls", calls=list(step["calls"]))
        return AgentStep(type="assistant", content=str(step.get("content") or ""))


def _registry(results: list[dict]) -> ToolRegistry:
    queues: dict[str, list[dict]] = {{}}
    for item in results:
        queues.setdefault(str(item["tool"]), []).append(item)
    tools = []
    for name, queue in queues.items():

        def _run(name: str = name, queue: list[dict] = queue):
            def run(_data, _context) -> ToolResult:
                item = queue.pop(0)
                return ToolResult(ok=bool(item["ok"]), output=str(item["output"]))

            return run

        tools.append(
            ToolDefinition(
                name=name,
                description="replay",
                input_schema={{"type": "object"}},
                validator=lambda value: value,
                run=_run(),
            )
        )
    return ToolRegistry(tools)


def test_replay_session() -> None:
    messages: list[dict] = [{{"role": "system", "content": SYSTEM}}]
    for turn in TURNS:
        model = ScriptedModel(turn["steps"])
        messages.append({{"role": "user", "content": turn["user"]}})
        before = len(messages)
        messages = run_agent_turn(
            model=model,
            tools=_registry(turn["results"]),
            messages=messages,
            cwd=".",
        )
        assert model.calls == len(turn["steps"])
        made = [
            (item["toolName"], item["input"])
            for item in messages[before:]
            if item.get("role") == "assistant_tool_call"
        ]
        expected = [
            (call["toolName"], call["input"])
            for step in turn["steps"]
            if step["type"] == "tool_calls"
            for call in step["calls"]
        ]
        assert made == expected
    last = TURNS[-1]["steps"][-1]
    if last["type"] == "assistant":
        assert messages[-1]["content"] == last["content"]
'''


def _turn_from_segment(
    user: str,
    segment: list[ChatMessage],
    model_rows: list[dict[str, Any]],
) -> dict[str, Any]:
    calls: list[dict[str, Any]] = []
    results: list[dict[str, Any]] = []
    assistants: list[str] = []
    for message in segment:
        role = message.get("role")
        if role == "assistant_tool_call":
            calls.append(
                {
                    "id": str(message.get("toolUseId") or "tool"),
                    "toolName": str(message.get("toolName") or ""),
                    "input": message.get("input") if isinstance(message.get("input"), dict) else {},
                }
            )
        elif role == "tool_result":
            output = str(message.get("content") or "")
            if len(output) > RESULT_LIMIT:
                output = output[:RESULT_LIMIT] + "\n...[fixture truncated]"
            results.append(
                {
                    "tool": str(message.get("toolName") or ""),
                    "ok": not bool(message.get("isError")),
                    "output": output,
                }
            )
        elif role == "assistant":
            assistants.append(str(message.get("content") or ""))
    steps: list[dict[str, Any]] = []
    for group in _chunk_calls(calls, model_rows):
        steps.append({"type": "tool_calls", "calls": group})
    for content in assistants:
        steps.append({"type": "assistant", "content": content})
    if not steps:
        steps.append({"type": "assistant", "content": ""})
    return {"user": user, "steps": steps, "results": results}


def _chunk_calls(calls: list[dict[str, Any]], model_rows: list[dict[str, Any]]) -> list[list[dict[str, Any]]]:
    sizes = [
        len(row.get("calls") or [])
        for row in model_rows
        if row.get("decision") == "tool_calls"
    ]
    sizes = [size if size > 0 else 1 for size in sizes]
    if not calls:
        return []
    if sum(sizes) != len(calls):
        return [[call] for call in calls]
    grouped: list[list[dict[str, Any]]] = []
    index = 0
    for size in sizes:
        grouped.append(calls[index : index + size])
        index += size
    return grouped


def _tape_groups(rows: list[dict[str, Any]], session_id: str) -> list[list[dict[str, Any]]]:
    groups: list[list[dict[str, Any]]] = []
    current: list[dict[str, Any]] = []
    started = False
    for row in rows:
        if session_id and str(row.get("session") or "") not in {"", session_id}:
            continue
        if row.get("via"):
            continue
        if row.get("kind") == "user":
            if started:
                groups.append(current)
            current = []
            started = True
            continue
        if row.get("kind") == "model" and started:
            current.append(row)
    if started:
        groups.append(current)
    return groups
